Mugurtham.Service/Areas/SangamAdmin/Controllers/MVC/SangamAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mugurtham.Service.Controllers;
using System.IO;
using Mugurtham.Common.Utilities;

namespace Mugurtham.Service.Areas.SangamAdmin.Controllers.MVC
{
    [MugurthamAuthorizeAttribute(Mugurtham.Core.Constants.RoleIDForSangamAdmin)]
    public class SangamAdminController :  MugurthamBaseController
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult Settings()
        {
            return View();
        }
        public ActionResult SangamAdminProfiles()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveSangamLogo(HttpPostedFileBase file)
        {
            Mugurtham.Core.Login.LoggedInUser objLoggedIn = (Mugurtham.Core.Login.LoggedInUser)Session["LoggedInUser"];
            if (file != null && file.ContentLength > 0)
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Images/Mugurtham/Sangam/Logo"),
                                              objLoggedIn.sangamID + Path.GetExtension(Path.GetFileName(file.FileName)));
                    file.SaveAs(path);
                    Mugurtham.Core.Sangam.SangamCore objSangamCore = new Core.Sangam.SangamCore();
                    using (objSangamCore as IDisposable)
                    {
                        Mugurtham.Core.Sangam.SangamCoreEntity objSangamCoreEntity = new Core.Sangam.SangamCoreEntity();
                        using (objSangamCoreEntity as IDisposable)
                        {
                            objSangamCoreEntity = objSangamCore.GetByID(objLoggedIn.sangamID);
                            objSangamCoreEntity.LogoPath = "/Images/Mugurtham/Sangam/Logo/" + objLoggedIn.sangamID + Path.GetExtension(Path.GetFileName(file.FileName));
                            objSangamCore.Edit(ref objSangamCoreEntity);
                        }
                        objSangamCoreEntity = null;
                    }
                    objSangamCore = null;
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            else
            {
                ViewBag.Message = "You have not specified a file.";
            }
            return Redirect("/Mugurtham#/SangamAdminSettings");
        }

        [HttpPost]
        public ActionResult SaveSangamBanner(HttpPostedFileBase file)
        {
            Mugurtham.Core.Login.LoggedInUser objLoggedIn = (Mugurtham.Core.Login.LoggedInUser)Session["LoggedInUser"];
            if (file != null && file.ContentLength > 0)
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Images/Mugurtham/Sangam/Banner"),
                                               objLoggedIn.sangamID + Path.GetExtension(Path.GetFileName(file.FileName)));
                    file.SaveAs(path);
                    Mugurtham.Core.Sangam.SangamCore objSangamCore = new Core.Sangam.SangamCore();
                    using (objSangamCore as IDisposable)
                    {
                        Mugurtham.Core.Sangam.SangamCoreEntity objSangamCoreEntity = new Core.Sangam.SangamCoreEntity();
                        using(objSangamCoreEntity as IDisposable)
                        {
                            objSangamCoreEntity = objSangamCore.GetByID(objLoggedIn.sangamID);
                            objSangamCoreEntity.BannerPath = "/Images/Mugurtham/Sangam/Banner/" + objLoggedIn.sangamID + Path.GetExtension(Path.GetFileName(file.FileName));
                            objSangamCore.Edit(ref objSangamCoreEntity);
                        }
                        objSangamCoreEntity = null;
                    }
                    objSangamCore = null;
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            else
            {
                ViewBag.Message = "You have not specified a file.";
            }
            return Redirect("/Mugurtham#/SangamAdminSettings");
        }
    }
}

Mugurtham.Service/Areas/SangamAdmin/Controllers/MVC/SangamUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mugurtham.Service.Controllers;
using Mugurtham.Common.Utilities;

namespace Mugurtham.Service.Areas.SangamAdmin.Controllers.MVC
{
    [MugurthamAuthorizeAttribute(Mugurtham.Core.Constants.RoleIDForSangamAdmin)]
    public class SangamUserController : MugurthamBaseController
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            return View();
        }
        public ActionResult Form()
        {
            return View();
        }
    }
}

Mugurtham.Service/Areas/SangamAdmin/Views/SangamAdmin/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Areas/SangamAdmin/Views/Shared/LayoutSangamAdmin.cshtml";
}

<div class="col-sm-12" data-ng-init="getChartData();">
    <h3>Sangam Admin Dashboard</h3>
    <hr />
</div>
 


<h3>This year sales by Month</h3>
<div class="col-lg-12">
        <div class="col-lg-9" id="divPieSales" style="height: 300px; width: 400px;"></div>
    <div class="col-lg-3" id="divBarReport" style="height: 300px; width: 350px;"></div>
</div>
<div class="col-lg-12">
    <div class="col-lg-3" id="divStackStar" style="height: 300px; width: 750px;"></div>
</div>

Mugurtham.Service/Areas/SangamAdmin/Views/SangamAdmin/SangamAdminProfiles.cshtml
@{
    Layout = "~/Areas/SangamAdmin/Views/Shared/LayoutSangamAdmin.cshtml";
    Mugurtham.Core.Login.LoggedInUser objLoggedIn = (Mugurtham.Core.Login.LoggedInUser)Session["LoggedInUser"];
}

<div id="divContainer">
    <p class="lead">Profiles List</p>
    <hr />
    <div class="col-lg-12" data-ng-init="getAllProfilesBySangam();">
        <ul class="breadcrumb">
            <li >Home</li>
            <li class="active">List</li>
        </ul>
    </div>
    
    <div class="col-lg-12">
        <table>
            <tr>
                <td>
                <td>&nbsp;Sangam Profile ID &nbsp;</td>
                <td>
                    <input type="text" class="form-control" ng-model="frmData[0].SangamProfiledID" placeholder="Sangam ProfileID">
                </td>
                <td>&nbsp;Mugurtham Profile ID &nbsp;</td>
                <td>
                    <input type="text" class="form-control" ng-model="frmData[0].MugurthamProfileID" placeholder="Mugurtham ProfileID">
                </td>
                <td>
                    <label for="Marital Status" class="col-lg-3 control-label">Gender</label>
                    <div class="col-lg-9">
                        <select class="form-control" id="ddlGender" ng-model="frmData[0].Gender">
                            <option value="">--Select--</option>
                            <option value="groom">groom</option>
                            <option value="bride">bride</option>
                        </select>
                    </div>
                </td>
            </tr>
            <tr>
            </tr>
        </table>
    </div>

    <div class="col-lg-12">
        <br />
    </div>
    <table class="mugurthamTable table-striped table-bordered table-hover FormShadow">
        <thead>
            <tr>
                <th>Sangam Profile ID</th>
                <th>Mugurtham Profile ID</th>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
            </tr>
        </thead>
        <tbody class="example-animate-container">
            <tr class="animate-repeat" ng-repeat="data in AllProfiles.ProfileBasicInfoViewCoreEntityList | filter: {SangamID: '@objLoggedIn.sangamID', MugurthamProfileID: frmData[0].MugurthamProfileID, SangamProfileID: frmData[0].SangamProfiledID,Gender: frmData[0].Gender} | orderBy:'MugurthamProfileID'">

                <td><a ng-click="setProfileIDBySangamAdminForProfilePic(data.MugurthamProfileID);" href="#/BasicInfo/{{data.MugurthamProfileID }}">{{data.SangamProfileID }}</a></td>
                <td><a ng-click="setProfileIDBySangamAdminForProfilePic(data.MugurthamProfileID);" href="#/BasicInfo/{{data.MugurthamProfileID }}">{{data.MugurthamProfileID }}</a></td>
                <td>{{data.Name }}</td>
                <td>{{data.Age }}</td>
                <td>{{data.Gender }}</td>

            </tr>
        </tbody>        
    </table>
    
</div>

Mugurtham.Service/Areas/SangamAdmin/Views/SangamAdmin/Settings.cshtml
@{
    ViewBag.Title = "Settings";
    Layout = "~/Areas/SangamAdmin/Views/Shared/LayoutSangamAdmin.cshtml";    
}

<h2>Settings</h2>
<hr />
<ul class="breadcrumb">
    <li class="active">Home</li>
</ul>
 <div>
        @using (Html.BeginForm("SaveSangamLogo",
                        "SangamAdmin",  
                        FormMethod.Post,  
                        new { enctype = "multipart/form-data" }))  
{                    
    <label for="file">Upload Sangam Logo:</label>  
    <input type="file" name="file" id="file"/><br><br>  
    <input type="submit" value="Upload Sangam Logo"/>  
    <br><br>  
    @ViewBag.Message  
}
    </div>

 <div>
        @using (Html.BeginForm("SaveSangamBanner",
                        "SangamAdmin",  
                        FormMethod.Post,  
                        new { enctype = "multipart/form-data" }))  
{                    
    <label for="file">Upload Sangam Banner:</label>  
    <input type="file" name="file" id="file"/><br><br>  
    <input type="submit" value="Upload Sangam Banner"/>  
    <br><br>  
    @ViewBag.Message  
}
    </div>